import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { FileLock2, ShieldCheck, Scale, UserCheck } from "lucide-react";
import "./TermsConditions.css";

const effectiveDate = "27 August 2026";

export default function TermsConditions() {
  return <main className="terms-page container">
    <section className="terms-hero">
      <Badge className="soft-badge">SERVICE TERMS</Badge>
      <h1>Terms &amp; <em>Conditions</em></h1>
      <p>These terms explain the permitted use of Excel Master File Tool and the privacy boundaries for your workbook processing.</p>
      <h2 lang="my" className="terms-title-my">စည်းမျဉ်းများနှင့် <em>သတ်မှတ်ချက်များ</em></h2>
      <p lang="my" className="terms-copy-my">ဤစည်းမျဉ်းများသည် Excel Master File Tool ကို အသုံးပြုခွင့်နှင့် သင့် workbook များကို စီမံဆောင်ရွက်ရာတွင် လိုက်နာသည့် ကိုယ်ရေးအချက်အလက် ကာကွယ်မှုဆိုင်ရာ ကန့်သတ်ချက်များကို ရှင်းပြထားပါသည်။</p>
      <span>Effective date: {effectiveDate}</span>
      <span lang="my" className="terms-date-my">အသက်ဝင်သည့်ရက်စွဲ - ၂၀၂၆ ခုနှစ်၊ ဩဂုတ်လ ၂၇ ရက်</span>
    </section>

    <Card className="terms-notice"><CardContent><Scale size={20}/><div><strong>Working terms — review before relying on them commercially</strong><p>These are general service terms, not legal advice. Please have a qualified lawyer review them before using them as binding terms for a business or regulated service.</p><strong lang="my" className="terms-notice-my">အသုံးပြုခြင်းမပြုမီ စစ်ဆေးရန်</strong><p lang="my" className="terms-copy-my">ဤအချက်များသည် အထွေထွေ ဝန်ဆောင်မှုစည်းမျဉ်းများသာဖြစ်ပြီး ဥပဒေအကြံဉာဏ် မဟုတ်ပါ။ စီးပွားရေးလုပ်ငန်း သို့မဟုတ် စည်းမျဉ်းသတ်မှတ်ထားသော ဝန်ဆောင်မှုအတွက် အတည်ပြုစည်းမျဉ်းအဖြစ် အသုံးမပြုမီ အရည်အချင်းရှိသော ရှေ့နေတစ်ဦးထံ စစ်ဆေးပါ။</p></div></CardContent></Card>

    <section className="terms-grid" aria-label="Terms and conditions in English and Myanmar">
      <article><span><FileLock2 size={18}/></span><h2>1. Service and files</h2><p>The tool helps you transform compatible CSV and XLSX workbooks into a preview and downloadable output. Files are processed temporarily in memory for the requested workflow; the application does not intentionally store uploaded workbooks, worksheet cells, previews, or generated workbook bytes in its database or file storage.</p><h3 lang="my">၁။ ဝန်ဆောင်မှုနှင့် ဖိုင်များ</h3><p lang="my" className="terms-copy-my">ဤကိရိယာသည် အသုံးပြုနိုင်သော CSV နှင့် XLSX workbook များကို အစမ်းကြည့်ရှုနိုင်ပြီး ဒေါင်းလုဒ်လုပ်နိုင်သော ရလဒ်အဖြစ် ပြောင်းလဲပေးပါသည်။ တောင်းဆိုထားသော workflow အတွက် ဖိုင်များကို memory ထဲတွင် ယာယီသာ စီမံဆောင်ရွက်ပါသည်။ အပ်လုဒ်တင်ထားသော workbook၊ worksheet cell၊ preview သို့မဟုတ် ထုတ်လုပ်ပြီး workbook byte များကို database သို့မဟုတ် file storage တွင် ရည်ရွယ်၍ မသိမ်းဆည်းပါ။</p></article>
      <article><span><UserCheck size={18}/></span><h2>2. Your responsibilities</h2><p>You are responsible for ensuring that you have permission to upload and process every workbook. Do not upload unlawful, harmful, malicious, or confidential data unless you are authorized to handle it and have assessed whether the service is suitable for that data.</p><h3 lang="my">၂။ သင့်တာဝန်များ</h3><p lang="my" className="terms-copy-my">workbook တစ်ခုချင်းစီကို အပ်လုဒ်တင်ခြင်းနှင့် စီမံဆောင်ရွက်ခြင်းအတွက် ခွင့်ပြုချက်ရှိကြောင်း သင်တာဝန်ယူရပါမည်။ ထိုဒေတာကို ကိုင်တွယ်ခွင့်ရှိပြီး ဝန်ဆောင်မှုသည် သင့်လျော်ကြောင်း သေချာစွာ စစ်ဆေးထားခြင်းမရှိပါက ဥပဒေမဲ့၊ အန္တရာယ်ရှိသော၊ မသမာသော သို့မဟုတ် လျှို့ဝှက်ဒေတာများကို မအပ်လုဒ်တင်ပါနှင့်။</p></article>
      <article><span><ShieldCheck size={18}/></span><h2>3. Accounts and privacy</h2><p>Account features are available only to the signed-in user. Editable profile values are encrypted before storage. Completed-process history contains limited metadata only, such as tool name, source filename metadata, totals, output filename, and time; you can manage retention, export your account data, or clear history from the account pages.</p><h3 lang="my">၃။ အကောင့်နှင့် ကိုယ်ရေးအချက်အလက်</h3><p lang="my" className="terms-copy-my">အကောင့်ဆိုင်ရာ လုပ်ဆောင်ချက်များကို ဝင်ရောက်ထားသော အသုံးပြုသူသာ အသုံးပြုနိုင်ပါသည်။ ပြင်ဆင်နိုင်သော profile အချက်အလက်များကို မသိမ်းဆည်းမီ encrypt ပြုလုပ်ပါသည်။ ပြီးစီးခဲ့သော လုပ်ဆောင်မှုမှတ်တမ်းတွင် tool အမည်၊ အရင်းအမြစ် ဖိုင်အမည် metadata၊ စုစုပေါင်း၊ output ဖိုင်အမည်နှင့် အချိန်ကဲ့သို့ အကန့်အသတ်ရှိသော metadata များသာ ပါဝင်ပါသည်။ သိမ်းဆည်းကာလကို စီမံနိုင်ပြီး အကောင့်ဒေတာကို export လုပ်ခြင်း သို့မဟုတ် မှတ်တမ်းရှင်းလင်းခြင်းကို account page မှ ပြုလုပ်နိုင်ပါသည်။</p></article>
      <article><span><FileLock2 size={18}/></span><h2>4. Acceptable use</h2><p>You must not attempt to bypass security controls, overload the service, probe other users’ data, reverse engineer protected services, or use the tool to distribute harmful content. Temporary request limits protect the service; when a limit is reached, wait for the displayed countdown before trying again.</p><h3 lang="my">၄။ လက်ခံနိုင်သော အသုံးပြုမှု</h3><p lang="my" className="terms-copy-my">လုံခြုံရေးထိန်းချုပ်မှုများကို ကျော်လွှားရန် ကြိုးပမ်းခြင်း၊ ဝန်ဆောင်မှုကို အလွန်အကျွံ အသုံးပြုခြင်း၊ အခြားအသုံးပြုသူ၏ ဒေတာကို စမ်းသပ်ရှာဖွေခြင်း၊ ကာကွယ်ထားသော ဝန်ဆောင်မှုကို reverse engineer ပြုလုပ်ခြင်း သို့မဟုတ် အန္တရာယ်ရှိသော အကြောင်းအရာ ဖြန့်ဝေရန် ဤကိရိယာကို အသုံးပြုခြင်း မပြုရပါ။ ယာယီ request limit များသည် ဝန်ဆောင်မှုကို ကာကွယ်ပေးပါသည်။ limit ရောက်ပါက ထပ်မံမကြိုးစားမီ ပြသထားသော countdown ကို စောင့်ပါ။</p></article>
      <article><span><Scale size={18}/></span><h2>5. Output review and availability</h2><p>You must review each preview and downloaded workbook before relying on it for payroll, compliance, reporting, or any other consequential purpose. The service is provided as available and may change, pause, or be updated to protect reliability and security.</p><h3 lang="my">၅။ ရလဒ်စစ်ဆေးခြင်းနှင့် ဝန်ဆောင်မှုရရှိနိုင်မှု</h3><p lang="my" className="terms-copy-my">လစာပေးချေမှု၊ စည်းမျဉ်းလိုက်နာမှု၊ report ပြုလုပ်မှု သို့မဟုတ် အရေးကြီးသော အခြားကိစ္စများတွင် မသုံးမီ preview နှင့် ဒေါင်းလုဒ်လုပ်ထားသော workbook တစ်ခုချင်းစီကို သင်စစ်ဆေးရပါမည်။ ဝန်ဆောင်မှုကို ရရှိနိုင်သလို ပံ့ပိုးပေးထားပြီး ယုံကြည်စိတ်ချရမှုနှင့် လုံခြုံရေးကို ကာကွယ်ရန် ပြောင်းလဲခြင်း၊ ခေတ္တရပ်နားခြင်း သို့မဟုတ် update ပြုလုပ်ခြင်းတို့ ရှိနိုင်ပါသည်။</p></article>
      <article><span><UserCheck size={18}/></span><h2>6. Updates to these terms</h2><p>Material updates will be published on this page with a revised effective date. Continuing to use the tool after an update means you accept the revised terms to the extent permitted by applicable law.</p><h3 lang="my">၆။ ဤစည်းမျဉ်းများ အပ်ဒိတ်ပြုလုပ်ခြင်း</h3><p lang="my" className="terms-copy-my">အရေးကြီးသော အပ်ဒိတ်များကို ပြင်ဆင်ထားသော အသက်ဝင်သည့်ရက်စွဲနှင့်အတူ ဤစာမျက်နှာတွင် ထုတ်ပြန်ပါမည်။ အပ်ဒိတ်ပြုလုပ်ပြီးနောက် ကိရိယာကို ဆက်လက်အသုံးပြုခြင်းသည် သက်ဆိုင်ရာဥပဒေမှ ခွင့်ပြုသည့်အတိုင်း ပြင်ဆင်ထားသော စည်းမျဉ်းများကို လက်ခံခြင်းဖြစ်ပါသည်။</p></article>
    </section>
  </main>;
}
