create table if not exists public.admin_user_action_history (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete restrict,
  actor_email text not null,
  target_user_id uuid not null,
  target_email text not null,
  action text not null check (action in ('ban', 'unban', 'delete')),
  status text not null default 'completed' check (status in ('completed', 'failed')),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists admin_user_action_history_created_at_idx
  on public.admin_user_action_history (created_at desc);

alter table public.admin_user_action_history enable row level security;

revoke all on table public.admin_user_action_history from anon, authenticated;

drop policy if exists "master account can read user action history" on public.admin_user_action_history;
create policy "master account can read user action history"
  on public.admin_user_action_history
  for select
  to authenticated
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'minnyo.work@gmail.com');

comment on table public.admin_user_action_history is
  'Protected audit history for Master Account ban, unban, and delete actions. It intentionally keeps deleted-user identity metadata after Auth deletion.';
